/** Real wood movement coefficient data, ported 1:1 from the reference calculator. */

export type WoodCategory = "hardwood" | "softwood" | "tropical";
export type StabilityLevel = "sehr gut" | "gut" | "mäßig" | "gering";

export interface WoodSpecies {
  id: string;
  nameDe: string;
  nameEn: string;
  botanical: string;
  category: WoodCategory;
  isNative: boolean;
  radialCoef: number; // % Schwund/Quellung je 1 % Feuchteänderung (quer zu den Jahresringen)
  tangentialCoef: number; // % Schwund/Quellung je 1 % Feuchteänderung (längs zu den Jahresringen)
  longitudinalCoef: number; // % je 1 % Feuchteänderung (typischerweise ~0,01 %)
  totalRadialShrinkage: number; // % vom Fasersättigungspunkt bis 0 % Holzfeuchte
  totalTangentialShrinkage: number; // % vom Fasersättigungspunkt bis 0 % Holzfeuchte
  fsp: number; // Fasersättigungspunkt in % (typischerweise ~28–32 %)
  density: number; // Rohdichte ρ12 bei 12 % Holzfeuchte in kg/m³
  stability: StabilityLevel;
  description: string;
  colorTone: string; // für die Einfärbung der Querschnittsvisualisierung
}

export const WOOD_SPECIES: WoodSpecies[] = [
  // --- Nadelhölzer (Softwoods) ---
  {
    id: "fichte",
    nameDe: "Fichte",
    nameEn: "Norway Spruce",
    botanical: "Picea abies",
    category: "softwood",
    isNative: true,
    radialCoef: 0.19,
    tangentialCoef: 0.36,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.6,
    totalTangentialShrinkage: 7.8,
    fsp: 30,
    density: 470,
    stability: "gut",
    description:
      "Das wichtigste Bau- und Konstruktionsholz Mitteleuropas. Leicht, elastisch und gut bearbeitbar mit mittlerem Quellverhalten.",
    colorTone: "#F3E5AB",
  },
  {
    id: "kiefer",
    nameDe: "Kiefer",
    nameEn: "Scots Pine",
    botanical: "Pinus sylvestris",
    category: "softwood",
    isNative: true,
    radialCoef: 0.19,
    tangentialCoef: 0.36,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.0,
    totalTangentialShrinkage: 7.7,
    fsp: 30,
    density: 520,
    stability: "gut",
    description: "Kernholzbaum mit markanter Maserung. Sehr vielseitig im Innen- und Außenbau.",
    colorTone: "#EED9A4",
  },
  {
    id: "laerche",
    nameDe: "Lärche",
    nameEn: "European Larch",
    botanical: "Larix decidua",
    category: "softwood",
    isNative: true,
    radialCoef: 0.16,
    tangentialCoef: 0.32,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.3,
    totalTangentialShrinkage: 8.2,
    fsp: 29,
    density: 590,
    stability: "gut",
    description:
      "Das schwerste und dauerhafteste einheimische Nadelholz. Hoher Harzgehalt, ideal für Fassaden und Terrassen.",
    colorTone: "#DE9F67",
  },
  {
    id: "douglasie",
    nameDe: "Douglasie",
    nameEn: "Douglas Fir",
    botanical: "Pseudotsuga menziesii",
    category: "softwood",
    isNative: false,
    radialCoef: 0.15,
    tangentialCoef: 0.27,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.8,
    totalTangentialShrinkage: 7.6,
    fsp: 28,
    density: 540,
    stability: "gut",
    description:
      "Formstabil mit geringerem Quellverhalten als Fichte. Sehr beliebt im Außenbereich und für Terrassendielen.",
    colorTone: "#E5A574",
  },
  {
    id: "tanne",
    nameDe: "Tanne",
    nameEn: "Silver Fir",
    botanical: "Abies alba",
    category: "softwood",
    isNative: true,
    radialCoef: 0.14,
    tangentialCoef: 0.28,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.0,
    totalTangentialShrinkage: 7.6,
    fsp: 31,
    density: 450,
    stability: "gut",
    description:
      "Harzfrei, witterungsbeständiger als Fichte bei Nassbelastung. Traditionell im Saunabau und Dachbau.",
    colorTone: "#F5E7C8",
  },
  {
    id: "zirbe",
    nameDe: "Zirbe",
    nameEn: "Swiss Stone Pine",
    botanical: "Pinus cembra",
    category: "softwood",
    isNative: true,
    radialCoef: 0.13,
    tangentialCoef: 0.26,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 2.8,
    totalTangentialShrinkage: 5.7,
    fsp: 28,
    density: 400,
    stability: "sehr gut",
    description:
      "Äußerst formstabil und schwindarm. Typischer aromatischer Duft, geschätzt für Schlafzimmermöbel und Schnitzarbeiten.",
    colorTone: "#ECC89A",
  },
  {
    id: "western_red_cedar",
    nameDe: "Zeder",
    nameEn: "Western Red Cedar",
    botanical: "Thuja plicata",
    category: "softwood",
    isNative: false,
    radialCoef: 0.11,
    tangentialCoef: 0.22,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 2.4,
    totalTangentialShrinkage: 5.0,
    fsp: 27,
    density: 370,
    stability: "sehr gut",
    description:
      "Extrem geringes Schwindmaß und hervorragende Dauerhaftigkeit. Perfekt für Saunen, Fassaden und Schindeln.",
    colorTone: "#C98D65",
  },

  // --- Einheimische & europäische Laubhölzer (Hardwoods) ---
  {
    id: "eiche",
    nameDe: "Eiche",
    nameEn: "European Oak",
    botanical: "Quercus robur / Q. petraea",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.18,
    tangentialCoef: 0.34,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.3,
    totalTangentialShrinkage: 8.9,
    fsp: 30,
    density: 690,
    stability: "gut",
    description:
      "Der Klassiker des Möbel- und Treppenbaus. Hohe Festigkeit, edle Maserung und gutes Stehvermögen.",
    colorTone: "#CDB188",
  },
  {
    id: "buche",
    nameDe: "Buche",
    nameEn: "European Beech",
    botanical: "Fagus sylvatica",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.22,
    tangentialCoef: 0.44,
    longitudinalCoef: 0.013,
    totalRadialShrinkage: 5.8,
    totalTangentialShrinkage: 11.8,
    fsp: 32,
    density: 720,
    stability: "gering",
    description:
      "Achtung: Sehr starkes Arbeiten! Buche reagiert extrem empfindlich auf Feuchteschwankungen und neigt zum Verwerfen.",
    colorTone: "#E4A882",
  },
  {
    id: "esche",
    nameDe: "Esche",
    nameEn: "European Ash",
    botanical: "Fraxinus excelsior",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.19,
    tangentialCoef: 0.35,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.8,
    totalTangentialShrinkage: 8.2,
    fsp: 30,
    density: 680,
    stability: "gut",
    description:
      "Sehr zäh, elastisch und biegefest. Häufig genutzt für Werkzeugstiele, Sportgeräte, Dielen und Treppen.",
    colorTone: "#E8D2AF",
  },
  {
    id: "ahorn_berg",
    nameDe: "Ahorn",
    nameEn: "Sycamore Maple",
    botanical: "Acer pseudoplatanus",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.16,
    tangentialCoef: 0.3,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.8,
    totalTangentialShrinkage: 8.0,
    fsp: 30,
    density: 620,
    stability: "gut",
    description: "Helles, feines Holz mit seidigem Glanz. Sehr beliebt im feinen Innenausbau und Instrumentenbau.",
    colorTone: "#F3E9CE",
  },
  {
    id: "hard_maple",
    nameDe: "Ahorn (Amerikanisch)",
    nameEn: "Sugar Maple",
    botanical: "Acer saccharum",
    category: "hardwood",
    isNative: false,
    radialCoef: 0.19,
    tangentialCoef: 0.36,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.8,
    totalTangentialShrinkage: 9.9,
    fsp: 29,
    density: 700,
    stability: "mäßig",
    description: "Sehr hart und abriebfest. Typisch für Bowlingbahnen, Schneidebretter und Parkettböden.",
    colorTone: "#EBDCB9",
  },
  {
    id: "nussbaum_euro",
    nameDe: "Nussbaum",
    nameEn: "European Walnut",
    botanical: "Juglans regia",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.18,
    tangentialCoef: 0.28,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.3,
    totalTangentialShrinkage: 7.5,
    fsp: 28,
    density: 640,
    stability: "sehr gut",
    description:
      "Exklusives Möbelholz mit herausragendem Stehvermögen. Schwindet und quillt vergleichsweise wenig.",
    colorTone: "#7D5C43",
  },
  {
    id: "nussbaum_black",
    nameDe: "Nussbaum (Amerikanisch)",
    nameEn: "Black Walnut",
    botanical: "Juglans nigra",
    category: "hardwood",
    isNative: false,
    radialCoef: 0.18,
    tangentialCoef: 0.27,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.1,
    totalTangentialShrinkage: 7.8,
    fsp: 28,
    density: 610,
    stability: "sehr gut",
    description: "Dunkelbraun mit Schokoton. Exzellentes Stehvermögen, minimales Verzugsrisiko.",
    colorTone: "#624A35",
  },
  {
    id: "kirschbaum_euro",
    nameDe: "Kirschbaum",
    nameEn: "European Cherry",
    botanical: "Prunus avium",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.17,
    tangentialCoef: 0.3,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.0,
    totalTangentialShrinkage: 8.5,
    fsp: 29,
    density: 600,
    stability: "gut",
    description: "Warm rötlicher Ton, dichte Struktur. Ausgezeichnetes Möbel- und Furnierholz.",
    colorTone: "#C7754B",
  },
  {
    id: "robinie",
    nameDe: "Robinie",
    nameEn: "Black Locust",
    botanical: "Robinia pseudoacacia",
    category: "hardwood",
    isNative: false,
    radialCoef: 0.2,
    tangentialCoef: 0.34,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.4,
    totalTangentialShrinkage: 8.1,
    fsp: 27,
    density: 740,
    stability: "gut",
    description:
      "Höchste Dauerhaftigkeitsklasse (Klasse 1) unter den in Europa wachsenden Hölzern. Schwer und witterungsfest.",
    colorTone: "#BA9C5E",
  },
  {
    id: "birke",
    nameDe: "Birke",
    nameEn: "Silver Birch",
    botanical: "Betula pendula",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.21,
    tangentialCoef: 0.3,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 5.3,
    totalTangentialShrinkage: 7.8,
    fsp: 30,
    density: 650,
    stability: "mäßig",
    description: "Helles, zähes Holz. Hauptsächlich für Multiplex, Drechselarbeiten und skandinavisches Möbeldesign.",
    colorTone: "#F4E9D0",
  },
  {
    id: "erle",
    nameDe: "Erle",
    nameEn: "Black Alder",
    botanical: "Alnus glutinosa",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.16,
    tangentialCoef: 0.3,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.4,
    totalTangentialShrinkage: 9.3,
    fsp: 30,
    density: 530,
    stability: "gut",
    description:
      "Weiches Laubholz mit gleichmäßiger Struktur. Unter Wasser extrem haltbar (Venedig-Pfähle). Beliebt im Gitarrenbau.",
    colorTone: "#DE9C68",
  },
  {
    id: "linde",
    nameDe: "Linde",
    nameEn: "Basswood / Lime",
    botanical: "Tilia cordata / T. platyphyllos",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.18,
    tangentialCoef: 0.31,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 5.5,
    totalTangentialShrinkage: 9.1,
    fsp: 32,
    density: 530,
    stability: "mäßig",
    description: "Das klassische Bildhauer- und Schnitzholz. Gleichmäßige Struktur in alle Richtungen.",
    colorTone: "#EDE0C5",
  },
  {
    id: "ulme",
    nameDe: "Ulme",
    nameEn: "Elm",
    botanical: "Ulmus carpinifolia / U. glabra",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.18,
    tangentialCoef: 0.28,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.2,
    totalTangentialShrinkage: 8.8,
    fsp: 30,
    density: 640,
    stability: "gut",
    description: "Lebhafte Textur, zäh und schwer spaltbar. Ein Klassiker im traditionellen Möbelbau.",
    colorTone: "#A8794F",
  },
  {
    id: "kastanie_edel",
    nameDe: "Kastanie",
    nameEn: "Sweet Chestnut",
    botanical: "Castanea sativa",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.15,
    tangentialCoef: 0.28,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.1,
    totalTangentialShrinkage: 7.4,
    fsp: 29,
    density: 590,
    stability: "sehr gut",
    description:
      "Sehr dauerhaft und formstabil durch hohen Gerbstoffgehalt. Ähnelt optisch Eiche, splittert jedoch weniger.",
    colorTone: "#B59368",
  },
  {
    id: "hainbuche",
    nameDe: "Hainbuche",
    nameEn: "Hornbeam",
    botanical: "Carpinus betulus",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.24,
    tangentialCoef: 0.44,
    longitudinalCoef: 0.015,
    totalRadialShrinkage: 6.8,
    totalTangentialShrinkage: 11.5,
    fsp: 31,
    density: 830,
    stability: "gering",
    description:
      'Eines der härtesten einheimischen Hölzer ("Eisenholz"). Arbeitet stark, extrem verschleißfest (Hobelsohlen).',
    colorTone: "#E5D5BA",
  },
  {
    id: "birnbaum",
    nameDe: "Birnbaum",
    nameEn: "Pear Wood",
    botanical: "Pyrus communis",
    category: "hardwood",
    isNative: true,
    radialCoef: 0.16,
    tangentialCoef: 0.32,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.3,
    totalTangentialShrinkage: 8.5,
    fsp: 29,
    density: 690,
    stability: "gut",
    description:
      "Porenlos feines, samtiges Edelholz. Geschätzt für Reißzeuge, Zeichenlineale und exklusiven Möbelbau.",
    colorTone: "#C98F6B",
  },

  // --- Tropen- & Überseehölzer (Tropical / Exotic) ---
  {
    id: "teak",
    nameDe: "Teak",
    nameEn: "Teak",
    botanical: "Tectona grandis",
    category: "tropical",
    isNative: false,
    radialCoef: 0.12,
    tangentialCoef: 0.22,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 2.2,
    totalTangentialShrinkage: 4.0,
    fsp: 26,
    density: 650,
    stability: "sehr gut",
    description:
      "Goldstandard für Formstabilität und Wetterbeständigkeit. Hoher Kautschuk- und Ölgehalt. Unübertroffen im Bootsbau.",
    colorTone: "#946638",
  },
  {
    id: "iroko",
    nameDe: "Iroko",
    nameEn: "Iroko",
    botanical: "Milicia excelsa",
    category: "tropical",
    isNative: false,
    radialCoef: 0.14,
    tangentialCoef: 0.24,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 2.8,
    totalTangentialShrinkage: 5.4,
    fsp: 26,
    density: 650,
    stability: "sehr gut",
    description: "Wird oft als Teak-Alternative eingesetzt. Sehr formstabil und dauerhaft für Gartenmöbel und Fenster.",
    colorTone: "#A8803F",
  },
  {
    id: "mahagoni",
    nameDe: "Mahagoni",
    nameEn: "Honduran Mahogany",
    botanical: "Swietenia macrophylla",
    category: "tropical",
    isNative: false,
    radialCoef: 0.13,
    tangentialCoef: 0.2,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.0,
    totalTangentialShrinkage: 4.6,
    fsp: 27,
    density: 560,
    stability: "sehr gut",
    description: "Weltberühmt für legendäre Formstabilität und Tiefenglanz. Schwindet und quillt minimal.",
    colorTone: "#96482F",
  },
  {
    id: "sipo",
    nameDe: "Sipo",
    nameEn: "Sipo / Utile",
    botanical: "Entandrophragma utile",
    category: "tropical",
    isNative: false,
    radialCoef: 0.17,
    tangentialCoef: 0.26,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.5,
    totalTangentialShrinkage: 7.2,
    fsp: 28,
    density: 660,
    stability: "gut",
    description: "Klassisches Fensterbau- und Konstruktionsholz im gehobenen Innenausbau.",
    colorTone: "#8A4832",
  },
  {
    id: "meranti_dark",
    nameDe: "Meranti",
    nameEn: "Dark Red Meranti",
    botanical: "Shorea curtisii",
    category: "tropical",
    isNative: false,
    radialCoef: 0.16,
    tangentialCoef: 0.29,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.8,
    totalTangentialShrinkage: 7.9,
    fsp: 28,
    density: 670,
    stability: "gut",
    description: "Sehr weit verbreitet im europäischen Fenster- und Haustürenbau.",
    colorTone: "#9B5542",
  },
  {
    id: "wenge",
    nameDe: "Wenge",
    nameEn: "Wenge",
    botanical: "Millettia laurentii",
    category: "tropical",
    isNative: false,
    radialCoef: 0.18,
    tangentialCoef: 0.31,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 3.8,
    totalTangentialShrinkage: 7.0,
    fsp: 27,
    density: 850,
    stability: "gut",
    description: "Sehr dunkles, fast schwarzes Edelholz mit hoher Härte und auffälliger Partiturnadelung.",
    colorTone: "#382B24",
  },
  {
    id: "bangkirai",
    nameDe: "Bangkirai",
    nameEn: "Bangkirai",
    botanical: "Shorea laevis",
    category: "tropical",
    isNative: false,
    radialCoef: 0.23,
    tangentialCoef: 0.38,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 4.8,
    totalTangentialShrinkage: 9.5,
    fsp: 28,
    density: 950,
    stability: "mäßig",
    description:
      "Sehr schweres Terrassenholz. Arbeitet spürbar, daher sind ausreichende Abstände (mind. 6–8 mm) bei Dielen zwingend!",
    colorTone: "#8E6845",
  },
  {
    id: "cumaru",
    nameDe: "Cumaru",
    nameEn: "Cumaru",
    botanical: "Dipteryx odorata",
    category: "tropical",
    isNative: false,
    radialCoef: 0.22,
    tangentialCoef: 0.35,
    longitudinalCoef: 0.01,
    totalRadialShrinkage: 5.3,
    totalTangentialShrinkage: 7.7,
    fsp: 26,
    density: 1050,
    stability: "gut",
    description: "Extrem hartes und witterungsbeständiges Terrassenholz mit hoher Tragfähigkeit.",
    colorTone: "#825638",
  },
];
