// Ported from the Drive reference's presets.ts (Terrassendielen-Rechner AI Studio export).

import { WoodPreset } from "./types";

export const WOOD_PRESETS: WoodPreset[] = [
  {
    id: "douglasie",
    name: "Douglasie",
    subtitle: "Heimisch & bewährt",
    boardWidth: 145,
    thickness: 28,
    boardLength: 4.0,
    gap: 6,
    recommendedJoistSpacing: 45,
    defaultPricePerMeter: 4.8,
    description: "Beliebteste heimische Holzart, lebendige Maserung mit rötlichem Farbton, Dauerhaftigkeitsklasse 3.",
  },
  {
    id: "laerche",
    name: "Sibirische / Europ. Lärche",
    subtitle: "Robust & harzreich",
    boardWidth: 140,
    thickness: 27,
    boardLength: 4.0,
    gap: 7,
    recommendedJoistSpacing: 45,
    defaultPricePerMeter: 6.2,
    description: "Hoher Harzgehalt, witterungsbeständig und formstabil. Fugenbreite min. 6-7 mm wegen Quellverhalten.",
  },
  {
    id: "bangkirai",
    name: "Bangkirai / Cumaru",
    subtitle: "Tropisches Hartholz",
    boardWidth: 145,
    thickness: 25,
    boardLength: 4.27,
    gap: 5,
    recommendedJoistSpacing: 50,
    defaultPricePerMeter: 12.5,
    description: "Extrem hart und langlebig (Dauerhaftigkeitsklasse 1-2). Vorbohren zwingend erforderlich!",
  },
  {
    id: "thermoesche",
    name: "Thermoesche",
    subtitle: "Edel & dimensionsstabil",
    boardWidth: 120,
    thickness: 21,
    boardLength: 3.6,
    gap: 5,
    recommendedJoistSpacing: 40,
    defaultPricePerMeter: 14.8,
    description: "Durch thermische Modifikation extrem formstabil und splitterarm. Dunkler, eleganter Farbton.",
  },
  {
    id: "wpc",
    name: "WPC / BPC Massivdiele",
    subtitle: "Pflegeleicht & barfußfreundlich",
    boardWidth: 140,
    thickness: 20,
    boardLength: 4.0,
    gap: 4,
    recommendedJoistSpacing: 40,
    defaultPricePerMeter: 9.5,
    description: "Holz-Polymer-Werkstoff, kein Vergrauen, splitterfrei. UK-Abstand max. 40 cm einhalten.",
  },
  {
    id: "kiefer_kdi",
    name: "Kiefer KDI (grün/braun)",
    subtitle: "Preiswerter Einstieg",
    boardWidth: 145,
    thickness: 27,
    boardLength: 3.0,
    gap: 6,
    recommendedJoistSpacing: 45,
    defaultPricePerMeter: 3.2,
    description: "Kesseldruckimprägniertes Nadelholz für budgetorientierte Terrassen. Regelmäßige Holzpflege empfohlen.",
  },
];
